authoritative;
#ddns-update-style interim;
#ignore client-updates;

# Point to your DNS server for DDNS updates
#zone isp108.lab. {
#  primary 1.108.1.2;
#}
#zone 108.1.in-addr.arpa. {
#  primary 1.108.1.2;
#}

# The subnet the DHCP server itself resides on (required for the daemon to start)
subnet 1.108.1.0 netmask 255.255.255.0 {
}

# The DHCP pool for the client network relayed by r4
subnet 1.108.2.0 netmask 255.255.255.0 {
    range 1.108.2.2 1.108.2.254;
    option routers 1.108.2.1;
    option subnet-mask 255.255.255.0;
    option domain-name-servers 1.108.1.2;
    #option domain-name "clients.isp108.lab";
    option domain-name "isp108.lab";
    # DDNS suffixing for dynamic clients
    #ddns-domainname "clients.isp108.lab.";
    #ddns-rev-domainname "in-addr.arpa.";
}
