frr version 9.1.3
frr defaults traditional
hostname as108r1
log file /var/log/frr/frr.log
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth0
 ip address 1.0.0.5/31
!
# Internal interface to r4 with standard OSPF Cost
interface eth1
 ip address 1.108.0.7/31
 ip ospf cost 10
 ip ospf network point-to-point
!
# Internal Interface to r2 with high OSPF Cost to prevent ECMP
interface eth2
 ip address 1.108.0.0/31
 ip ospf cost 30
 ip ospf network point-to-point
!
# Internal interface to r3 with standard OSPF Cost
interface eth3
 ip address 1.108.0.8/31
 ip ospf cost 10
 ip ospf network point-to-point
!
# Virtual loopback interface used for stabl OSPF/BGP router IDs
interface dummy0
 ip address 1.108.3.1/32
!
# OSPF configuration
router ospf
 ospf router-id 1.108.3.1
 network 1.108.0.0/20 area 0.0.0.0
# Originate default route with lower metric (10) to make r1 the primary Internet gateway
 default-information originate always metric 10
######
###### BGP COnfiguration for ASN 108
######
router bgp 108
 no bgp ebgp-requires-policy
 # eBGP peering with AS1
 neighbor 1.0.0.4 remote-as 1
 neighbor 1.0.0.4 description AS1
 neighbor 1.0.0.4 solo
 # iBGP peering with internal router r2
 neighbor 1.108.3.2 remote-as 108
 neighbor 1.108.3.2 description iBGP-r2
 # nsure iBGP session survives physical link failures by using dummy0
 neighbor 1.108.3.2 update-source dummy0
 !
 address-family ipv4 unicast
  # Advertise the primary aggregated AS108 network
  network 1.108.3.1/32
  aggregate-address 1.108.0.0/20 summary-only
  
  neighbor 1.0.0.4 soft-reconfiguration inbound

  # Apply inbound and oubound policies to the AS1 peer
  neighbor 1.0.0.4 route-map RMAP_IN_AS1 in
  neighbor 1.0.0.4 route-map RMAP_OUT_AS1 out
  # Ensure BGP routes remain reachable internally without OSPF redistribution
  neighbor 1.108.3.2 next-hop-self
 exit-address-family
!
# Prefix lists restricting outbound advertisments to specific subnets
ip prefix-list PFX_OUT seq 10 permit 1.108.0.0/20
ip prefix-list PFX_AS21 seq 10 permit 2.21.0.0/20
!
# Set LOCAL_PREF to 200 for incoming AS1 routes, making it the preferred exit
route-map RMAP_IN_AS1 permit 10
 set local-preference 200
!
# Attach BGP Community 1:200 to outgoing routes so AS1 sets a high preference for our network
route-map RMAP_OUT_AS1 permit 10
 match ip address prefix-list PFX_OUT
 set community 1:200
!
route-map RMAP_OUT_AS1 permit 20
 match ip address prefix-list PFX_AS21
 set as-path prepend 108 108 108
