options {
    directory "/var/cache/bind";
    recursion yes;
    allow-recursion { 127.0.0.1; 1.108.0.0/20; };
    allow-query { any; };
    dnssec-validation no;
    listen-on-v6 { none; };
};
zone "." { type hint; file "/etc/bind/db.root"; };
zone "isp108.lab"         { type master; file "/etc/bind/db.isp108.lab"; };
zone "108.1.in-addr.arpa" { type master; file "/etc/bind/db.isp108.1"; };
zone "localhost"        { type master; file "/etc/bind/db.local"; };
zone "127.in-addr.arpa" { type master; file "/etc/bind/db.127"; };
zone "0.in-addr.arpa"   { type master; file "/etc/bind/db.0"; };
zone "255.in-addr.arpa" { type master; file "/etc/bind/db.255"; };
