options {
    directory "/var/cache/bind";
    recursion yes;
    allow-query { any; };
    dnssec-validation auto;
    listen-on-v6 { any; };
};

zone "isp108.lab" {
    type master;
    file "/etc/bind/db.isp108.lab";
    allow-update { 1.108.1.3; }; # Permits DDNS updates from the DHCP server
};

zone "108.1.in-addr.arpa" {
    type master;
    file "/etc/bind/db.isp108.1";
    allow-update { 1.108.1.3; };
};
